import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Container, Box, Divider, Grid, Toolbar, TextField, Button, Typography } from '@mui/material'
import { TabContext, TabList, TabPanel } from '@mui/lab';
import Tab from '@mui/material/Tab';
import { useState } from 'react';

export default function Home() {
  const [value, setValue] = useState('1');
  const handleChange = (event, newValue) => {
    setValue(newValue);
  };
  return (

    <div className={styles.container}>
      <Head>
        <title>Flight Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{marginTop:'200px'}}>
        <div className={styles.headinfo}>
          <h1>WELCOME TO SASTO TICKETS</h1>
          <p>Home Of Domestic & International Tickets</p>
        </div>
        <Box >
          <TabContext value={value}>
            <Box sx={{ borderBottom:0.5, borderColor: 'divider'}}>
              <TabList onChange={handleChange} aria-label="basic tabs example">
                <Tab label="One Way" value="1" sx={{ bgcolor: "white",borderTopLeftRadius:"6px" ,borderTopRightRadius:"6px", width:'10px',height:'10px'}} />
                <Divider orientation="vertical" />
                <Divider orientation="vertical" />
                <Divider orientation="vertical" />
                <Divider orientation="vertical" />
                <Tab label="Round Trip" value="2" sx={{ bgcolor: "white",borderTopLeftRadius:"6px" ,borderTopRightRadius:"6px", width:'10px',height:'10px' }} />
                <Divider orientation="vertical" />
                <Divider orientation="vertical" />
                <Divider orientation="vertical" />
                <Divider orientation="vertical" />
                <Tab label="Multi City" value="3" sx={{ bgcolor: "white",borderTopLeftRadius:"6px" ,borderTopRightRadius:"6px", width:'10px',height:'10px'}} />
                <Divider orientation="vertical" />
                <Divider orientation="vertical" />
                <Divider orientation="vertical" />
                <Divider orientation="vertical" />
                <Tab label="Mountain Flight" value="4" sx={{ bgcolor: "white",borderTopLeftRadius:"6px" ,borderTopRightRadius:"6px", width:'10px',height:'10px'}} />
              </TabList>
            </Box>

            <TabPanel value='1' sx={{bgcolor:'white',boxShadow:'2'}} >
              tab1
              
            </TabPanel>
            <TabPanel value='2' sx={{bgcolor:'white'}}>
              tab2
            </TabPanel>
            <TabPanel value='3' sx={{bgcolor:'white' }}>
              tab3
            </TabPanel>
            <TabPanel value='4' sx={{bgcolor:'white'}}>
              tab4
            </TabPanel>
          </TabContext>
        </Box>
      </Container>
    </div>
  )
}
